Issue 79 implement data source insert convenience methods
jessesquires/JSQDataSourcesKit pull request #85
Opened 2016-12-20 10:31 UTC by psartzetakis

## Pull request checklist

- [x] All tests pass. 
- [x] Demo project builds and runs.
- [x] I have resolved merge conflicts.
- [x] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines) and [contributing guidelines](https://github.com/jessesquires/HowToContribute).

#### This fixes issue #79 

## What's in this pull request?
This pull request adds some` insert/append` methods to the `DataSouce`

2016-12-21 00:05 UTC, jessesquires commented on Source/DataSource.swift
> +        guard row <= numberOfItems(inSection: section) else { return }
should be `row <`, right ?

2016-12-21 00:15 UTC, jessesquires requested changes
Thanks @psartzetakis !

Just a few minor comments 💯

2016-12-21 00:15 UTC, jessesquires commented on Source/DataSource.swift
> +    }
👍

2016-12-21 00:15 UTC, jessesquires commented on Tests/DataSourceTests.swift
> +        XCTAssertNotNil(insertedIndex)
let's remove these 2 nil checks

2016-12-21 00:15 UTC, jessesquires commented on Tests/DataSourceTests.swift
> +        XCTAssertEqual(insertedIndex, ip.row, "New item should be at the requested index")
let's also test `Equal(dataSource[ip], newItem)`

2016-12-21 00:15 UTC, jessesquires commented on Tests/DataSourceTests.swift
> +        XCTAssertEqual(insertedIndex, sectionItems!.count - 1, "New item should be at the requested index")
same 2 comments as above

2016-12-21 00:15 UTC, jessesquires commented on Tests/DataSourceTests.swift
> +    func test_thatDataSource_doesntInsertData_atOutOfBounds_Section() {
nit: `..._doesNotInsert...`

2016-12-21 00:15 UTC, jessesquires commented on Tests/DataSourceTests.swift
> +        let contains = sectionItems!.contains(newItem)
let's just put this inline in the `assertFalse`

also, we use `sectionItems?` instead?

2016-12-21 00:31 UTC, psartzetakis commented on Source/DataSource.swift
> +        guard row <= numberOfItems(inSection: section) else { return }
Well if he have 2 rows (`row-0`, `row-1`) and the user wants an item at `row-2` then the `row` will be `2` and the `numberOfItems(inSection: section)` will be already `2`. So the `equality` is for `appending`, correct? Do I miss something..?🤔

2016-12-21 04:24 UTC, jessesquires commented on Source/DataSource.swift
> +        guard row <= numberOfItems(inSection: section) else { return }
oops, you're right. 😅 😊

2016-12-22 04:15 UTC, jessesquires approved these changes
Awesome! Thanks @psartzetakis ! 💯 🥇

2016-12-22 04:16 UTC, merged